image: docker:latest

variables:
  REPOSITORY_URL: 638678992927.dkr.ecr.ap-southeast-1.amazonaws.com/sample-service
  MAVEN_OPTS: -Dmaven.repo.local=/cache/.m2
  
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3
  stage: build
  cache:
    key: "$CI_BUILD_STAGE"
    paths:
      - /cache/.m2
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  script:
    - docker build -t $REPOSITORY_URL:latest .
    - docker push $REPOSITORY_URL:latest

  #except:
  #  - master