server:
  servlet:
    context-path: /
  port: 9200
spring:
  profiles:
    active:
      - ${BUMBLEBEE_SPRING_PROFILE:dev}
  application:
    name: sample-app-service

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/sample?stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
            use_jdbc_metadata_defaults: false

  flyway:
    locations: classpath:/db/migration
---
spring:
  profiles: alpha
  datasource:
    url: jdbc:postgresql://lb-alpha-db.cbsbgrmpqn4b.ap-southeast-1.rds.amazonaws.com:5432/sample?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
            use_jdbc_metadata_defaults: false

  flyway:
    locations: classpath:/db/migration